[package]
name = "rayn"
version = "0.1.0"
license-file = "LICENSE.md"
authors = ["Gray Olson <gray@grayolson.com>"]
edition = "2018"

[dependencies]
vek = "0.9"
image = "0.22"
rand = "0.7"
rayon = "1.2"
lazy_static = "1.2"
minterpolate = "0.4"
