[package]
name = "rayn"
version = "0.1.0"
license-file = "LICENSE.md"
authors = ["Gray Olson <gray@grayolson.com>"]

[dependencies]
# vek = { version =  "0.9.4", features = ["repr_simd"] }
vek = "0.9.4"
image = "0.19"
rand = "0.5.5"
rayon = "1.0.2"
